### PR TITLE
Move changes from the support branch to master

### PR DESCRIPTION
**Pull request by fyrchik**

### CODE REVIEW

**Review by carpawell — CHANGES_REQUESTED** [review]
Seems like the commit about `IsLocked` for metabase has been lost (see the tests).

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/J73mgT4Qsu9fLu3JivNkMDGgXynqbKdCR4Y5tjMBorTG Untar and use `allure open` to watch the report

**Review by carpawell — APPROVED** [review]

**Pull request merged**
