### PR TITLE
[#409] Storage service paths refactoring

### PR DESCRIPTION
**Pull request by fyrchik**
Separate User data and Service data:
 - /var/lib/neofs/storage for service persistence
 - /srv/neofs for user data

### CODE REVIEW

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/7VPszGcd5oJcAF8adMHmYHpErWvXdceyjQXhp63RU9o8 Untar and use `allure open` to watch the report

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/BVwmsrcwMRMfAxP2anDEYNNQZY76ycGyekot6rYkrKcH Untar and use `allure open` to watch the report

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/BheSTq1R1yEbb3v2nK46L6ewpBoXYZRsGSydr3AS7VJi Untar and use `allure open` to watch the report

**Comment by fyrchik** [comment]
@sami-nspcc working overtime is not good for mental health, take care!

**Review by realloc — APPROVED** [review]

**Pull request merged**
