### PR TITLE
[#1088] writecache: Fix small flushed mark

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Signed-off-by: ZhangTao1596 <zhangtao@ngd.neo.org>

### CODE REVIEW

**Review by fyrchik — COMMENTED** [review]
Nice catch! We need only to fix `c.evictObjects` argument before to remove right number of elements.
Otherwise, LGTM

**Comment by ZhangTao1596** [comment]
> Nice catch! We need only to fix `c.evictObjects` argument before to remove right number of elements. Otherwise, LGTM

Yeah. evictObjects argument needs fix too. Should I copy https://github.com/nspcc-dev/neofs-node/pull/1089/commits/f1a6262508a33b094432414596dce01795933d04 here?

**Comment by fyrchik** [comment]
@ZhangTao1596 yes, that works.

**Comment by ZhangTao1596** [comment]
> @ZhangTao1596 yes, that works.

Done.

**Review by fyrchik — APPROVED** [review]

**Pull request merged**
