### PR TITLE
Fix/Stop GC work on `Shard`'s `Close()`

### LINKED ISSUE #451: `iterator over metabase graveyard failed` message spam at application close
When remote RPC node closes connection, neofs-node application shuts down and requires restart to re-initialize listener component. When this happens, storage node floods log with `iterator over metabase graveyard failed`. It is expected error, since application closing open database files, however we don't need to spam hundred of these messages per second.

## Expected Behavior
Couple `iterator over metabase graveyard failed` errors before shut down.

## Current Behavior
```
2021-03-30T23:30:43.029+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.030+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.030+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.031+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.032+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.033+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.034+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.035+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.037+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.038+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.039+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
2021-03-30T23:30:43.040+0200    warn    shard/gc.go:174 iterator over metabase graveyard failed {"app_name": "neofs-node", "app_version": "v0.18.0-dirty", "error": "database not open"}
...
```

## Steps to Reproduce (for bugs)
I could not reproduce this in dev-env since we can't drop `WSClient` connection without neo-go node shutdown, unfortunately. However this situation happened at NeoFS testnet. Maybe we can find out the reason for such behavior in code.

### PR DESCRIPTION
**Pull request by carpawell**
Related to #451. Could not reproduce the issue locally, but this PR would stop GC in the same situation(not sure if it helps to restart node).

Added debug logs on shutdown.

### CODE REVIEW

**Comment by alexvanin** [comment]
Were you able to reproduce original issue?

**Comment by carpawell** [comment]
no, i could not

**Comment by cthulhu-rider** [comment]
If context is done only on application shutdown, it is easier to abort GC in `Shard.Close`.

**Comment by carpawell** [comment]
@cthulhu-rider, you mean smth like that: https://github.com/nspcc-dev/neofs-node/pull/745/commits/a11e1c2b4765f35cdf92ad1445aeeb086863347d

**Review by alexvanin — APPROVED** [review]

**Pull request merged**
