### PR TITLE
Feature/Allow non executable permissions in config

### LINKED ISSUE #646: data file are executable
```
rei # l /srv/neofs/data0/blobovnicza/0/0 
-rwxr-x--- 1 neofs-storage neofs-storage 10489856 Jun 24 04:40 /srv/neofs/data0/blobovnicza/0/0
```

### PR DESCRIPTION
**Pull request by carpawell**
Closes #646.

### CODE REVIEW

**Comment by alexvanin** [comment]
@anatoly-bogatyrev @532910 @realloc Can you provide some feedback on what you would expect as a NeoFS administrator from  node when it have non-existent dir in config path to blob stor?

Now node creats new dir with the same rights as blob stor files. Unlike blob stor files, dirs should be executable. This PR adds `--x--x--x` rights for new dirs, so you can specify 644 for blob stor files and dir will be 755. *However* 600 will turn into 711 dir. Looks odd. 

Maybe  `--x------` for dirs will solve the issue?

**Comment by 532910** [comment]
1. Yes, dirs must be executable
2. Permissions should follow umask

**Comment by carpawell** [comment]
according to https://github.com/nspcc-dev/neofs-node/issues/646#issuecomment-880055575, made `0660` as default(if `perm` is empty in config) permissions that would be also affected by `umask`. for dirs `--x--x---` is added(`0660` becomes `0770`)

if custom perms are presented in config, `--x--x---` is added for dirs and it is also affected by `umask`

is that expected behavior now?

**Comment by alexvanin** [comment]
> is that expected behavior now?

Let's stick with that. In case of different proposals, we will consider them in different issues.

**Pull request merged**
