### PR TITLE
workflow: disable all capturing

### PR DESCRIPTION
**Pull request by vvarg229**
Disabling all captures when running full system tests, as when running sanity tests after PR.

### CODE REVIEW

**Comment by vvarg229** [comment]
Verifying this workflow file when running ALL of the tests here:
https://github.com/vvarg229/neofs-node/actions/runs/5164038341/jobs/9302700755

**Review by roman-khimov — COMMENTED** [review]
I guess we'll just see logs in reports then?

**Comment by roman-khimov** [comment]
Why closing?

**Comment by vvarg229** [comment]
> Why closing?

I ran tests on the local repo and lots of failed tests.

This change does not reduce the number of logs and only complicates the code.
I don't think it's necessary.

**Pull request closed without merging**
