### PR TITLE
Replace local pkg policy by neofs-sdk policy

### LINKED ISSUE #116: Move placement policy parsers to SDK
QL parsers are quite useful for applications such as protocol gates or GUI apps. It provides human readable way to set up container policies. So it will be nice to have it in SDK library.

### PR DESCRIPTION
**Pull request by masterSplinter01**
Closes #116

Part of processing transfer of policy pkg to neofs-sdk repository.
Replaced local pkg policy by neofs-sdk policy
Replaced local dependency in neofs-cli.

### CODE REVIEW

**Comment by roman-khimov** [comment]
I think you can drop `github.com/nspcc-dev/neofs-node/pkg/policy` in the same commit.

**Comment by roman-khimov** [comment]
I mean physically remove the package from this repo.

**Comment by masterSplinter01** [comment]
I'm not sure that I should remove policy pkg now because authmate in s3 still importing it. 

After our conversation I made the conclusion that we decided to postpone changes in s3.

**Comment by roman-khimov** [comment]
> I'm not sure that I should remove policy pkg now because authmate in s3 still importing it.

It's not a problem for authmate because it's using the version of neofs-node specified in s3-gw go.mod file which is rather old and won't change in any way because of this PR. So it's OK to remove this package here.

**Comment by masterSplinter01** [comment]
Got it, removed.

**Comment by roman-khimov** [comment]
Some "closes #116" would also be useful here as it really fixes it.

**Review by roman-khimov — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]

**Review by alexvanin — CHANGES_REQUESTED** [review]
Can you modify commit header according to the style used in this repo? It should be 

```
[#116] Replace local pkg policy by neofs-sdk policy
```

or 

```
[#554] Replace local pkg policy by neofs-sdk policy
```

**Review by alexvanin — APPROVED** [review]

**Pull request merged**
