### PR TITLE
Upgrade minimum required Go version to `1.20`

### PR DESCRIPTION
**Pull request by cthulhu-rider**
* blocked by https://github.com/nspcc-dev/neofs-sdk-go/issues/553

### CODE REVIEW

**Comment by cthulhu-rider** [comment]
> pkg/util/salt.go can be improved

done

**Review by roman-khimov — APPROVED** [review]

**Comment by roman-khimov** [comment]
Conflicts.

**Review by carpawell — COMMENTED** [review]
Something is wrong with int tests. Otherwise, I am fine except `nolint` again.

**Comment by roman-khimov** [comment]
Conflicts now.

**Pull request merged**
