### PR TITLE
Sync first epoch duration at application startup

### LINKED ISSUE #679: Internal timer syncronization
In N3 Testnet RC3 we've got an issue with epoch 939. The epoch was frozen for some time, because internal epoch timers of Alphabet nodes were not synchronized. Notary transactions from one nodes failed before other nodes send them. In 240 blocks we could not collect more than 4 valid notary transaction (need at least 5). Even though Alphabet nodes synchronize timers after new epoch notification, some nodes may be restarted between epochs, which can lead to this. It will work the same way in notary disabled environment, because `votes` are valid only for [20 blocks](https://github.com/nspcc-dev/neofs-contract/blob/4d648431d6faabb1edd3c6ceb1f73aa8be955918/common/vote.go#L25). 

To solve this issue we need either:
- increase valid time of notary transaction (and more blocks for `votes` in contract) and make it **at least** amount of blocks per epoch (240 for testnet)
- store information about new epoch block in netmap contract so restarted node can synchronize it's clock.

I think first solution will be easier to implement, but it might work not that great in disabled notary environment. 
Second solution requires to modify netmap contract and tweak inner ring event scheduler.

### PR DESCRIPTION
**Pull request by alexvanin**
Closes #679 

At the startup, Inner Ring application calculates block duration before next epoch tick and processes new epoch event at this block.

### CODE REVIEW

**Comment by alexvanin** [comment]
To process single event in the future, I added `NewOneTickTimer` constructor in `morph/timer` (https://github.com/nspcc-dev/neofs-node/pull/708/commits/4ab91aedeb544482b6ac2967efc11101d412c25a). Maybe there are better solution for this.

**Review by carpawell — APPROVED** [review]
it took some time for me to get the idea of what `EpochBlock` returns, i had to go to read it in contract code
wouldn't it be better to add smth like "last" or "start" to the method name?

**Comment by alexvanin** [comment]
> wouldn't it be better to add smth like "last" or "start" or both to the method name?

I thought about that. `LastEpochBlock()` in the contract and in the code will be better, what do you think?

**Comment by carpawell** [comment]
> what do you think?

yes, it sounds better for me

**Pull request merged**
