### PR TITLE
Update neo-go version

### LINKED ISSUE #1417: morph: Bring back support of `big.Int` parameters
We've reverted `big.Int` support by morph client in #1416. We need to bring reverted changes back after https://github.com/nspcc-dev/neo-go/issues/2350 will be released. It's currently in milestone `v0.99.0`.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1417.

### CODE REVIEW

**Review by carpawell — APPROVED** [review]

**Comment by alexvanin** [comment]
I tried `experimental` branch and it doesn't work with neo-go v0.99.0 and corresponding chain dumps.

IR:
```
2022-06-06T09:36:33.912Z        warn    client/multi.go:115     switching to the next RPC node  {"error": "failed to write JSON request: json: error calling MarshalJSON for type smartcontract.Parameter: invalid int
eger value"}                                                                                                                                                                                                          
2022-06-06T09:36:33.912Z        info    innerring/innerring.go:368      failed to set group signer scope, continue with Global  {"error": "connection lost while waiting for the response"}                           
2022-06-06T09:36:33.912Z        error   client/multi.go:118     could not establish connection to any RPC node                                                                                                        
2022-06-06T09:36:33.912Z        warn    subscriber/subscriber.go:117    remote notification channel has been closed                                                                                                   
```

SN:
```
2022-06-06T09:37:05.343Z        warn    client/multi.go:115     switching to the next RPC node  {"error": "failed to write JSON request: json: error calling MarshalJSON for type smartcontract.Parameter: invalid int
eger value"}                                                                                                                                                                                                          
2022-06-06T09:37:05.343Z        info    neofs-node/morph.go:64  failed to set group signer scope, continue with Global  {"error": "connection lost while waiting for the response"}                                   
2022-06-06T09:37:05.343Z        error   client/multi.go:118     could not establish connection to any RPC node                                                                                                        
```

**Comment by fyrchik** [comment]
@alexvanin There was an error in morph NNS routines, used int64 instead of big.Int. Should be ok by now.

**Review by cthulhu-rider — APPROVED** [review]
Lets update `Unreleased`?

**Comment by fyrchik** [comment]
@cthulhu-rider will update, waiting until testing in devenv

**Review by cthulhu-rider — APPROVED** [review]

**Pull request merged**
