### PR TITLE
Reload `object.put.pool_size_remote` on SIGHUP

### PR DESCRIPTION
**Pull request by fyrchik**

### CODE REVIEW

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing. Build number is 3711

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from <a href="https://http.t5.fs.neo.org/get/FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/G8u7C1YDKbcvBegAmyy1bZK1NhAxAcYWFFeMDwrFJMkK">link</a>. Untar and use `allure open` to watch the report

**Comment by carpawell** [comment]
Does that wait for smth?

**Pull request closed without merging**
