### PR TITLE
@roschler Fixed a few typos and made some small improvements to the README.

### LINKED ISSUE #1137: Some typos and changes to the README.
I don't have write access so I can't make a pull request from my fork.  Here you will find the typos I fixed and some small rewrites I made to the README:

https://github.com/Android-Technologies-Inc/neofs-node/blob/master/README.md

### PR DESCRIPTION
**Pull request by realloc**
Close #1137

### CODE REVIEW

**Comment by realloc** [comment]
@roschler could you please add a sign-off line to your commit?

**Comment by roschler** [comment]
Is something like this sufficient?:
```
Signed-off-by: roschler
```

**Comment by realloc** [comment]
> Is something like this sufficient?:
> ```
> Signed-off-by: roschler
> ```
> 

There should also be an e-mail address.

**Comment by roschler** [comment]
> > Is something like this sufficient?:
> > ```
> > Signed-off-by: roschler
> > ```
> 
> There should also be an e-mail address.

Ok.  I'll make a new E-mail address so as to avoid spam.

**Review by alexvanin — APPROVED** [review]

**Pull request closed without merging**
