### PR TITLE
blobovnicza: Add benchmark to test different tree settings

### PR DESCRIPTION
**Pull request by cthulhu-rider**
current results:
```
goos: linux
goarch: amd64
pkg: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/blobovniczatree cpu: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
BenchmarkBlobovniczas_Put/tree=1x0-8                 100          53517515 ns/op         4609697 B/op        109 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                100          53417156 ns/op         5213543 B/op        119 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                 100          52124287 ns/op         5117641 B/op        158 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                 100          37065895 ns/op         2129467 B/op        188 allocs/op
```

according to test, tree management doesn't really help when number of layers is small. 4x4 showed better performance which is suspicious: right now it may be expected since we didn't try to optimize working with single DB instance as described in #2453.

P.S. in current test implementation, it's not obvious do we force to switch to other DBs or not. I tried to reach this using `-benchtime=100x` where `100` is `fullSizeLimit/singleObjectSize`.

### CODE REVIEW

**Comment by roman-khimov** [comment]
Here:
```
BenchmarkBlobovniczas_Put/tree=1x0-8                  57          27046852 ns/op         4786905 B/op        113 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  36          32247503 ns/op         4681081 B/op        109 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  40          31945389 ns/op         4855398 B/op        110 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 34          33063479 ns/op         5213628 B/op        120 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 37          33285487 ns/op         5195977 B/op        119 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 45          33081278 ns/op         5128587 B/op        120 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  44          30096345 ns/op         5198224 B/op        150 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  70          19756034 ns/op         4950343 B/op        151 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  74          20097768 ns/op         5203916 B/op        153 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  74          17488102 ns/op         2129200 B/op        183 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  70          16829594 ns/op         2128992 B/op        182 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  74          18119955 ns/op         2129311 B/op        187 allocs/op
```

But it's intended for small objects, so I've made:
```patch
--- a/pkg/local_object_storage/blobstor/blobovniczatree/put_test.go
+++ b/pkg/local_object_storage/blobstor/blobovniczatree/put_test.go
@@ -47,7 +47,7 @@ func benchmarkPutMN(b *testing.B, depth, width uint64) {
                nBlobovniczas *= width
        }
 
-       const objSizeLimit = 1 << 20
+       const objSizeLimit = 1 << 12
        const fullSizeLimit = 100 << 20
 
        bbcz := NewBlobovniczaTree(
@@ -66,6 +66,7 @@ func benchmarkPutMN(b *testing.B, depth, width uint64) {
                RawData: make([]byte, objSizeLimit),
        }
 
+       rand.Read(prm.RawData)
        b.ReportAllocs()
        b.ResetTimer()
 
@@ -74,7 +75,6 @@ func benchmarkPutMN(b *testing.B, depth, width uint64) {
        for i := 0; i < b.N; i++ {
                b.StopTimer()
                prm.Address = oidtest.Address()
-               rand.Read(prm.RawData)
                b.StartTimer()
 
                _, err = bbcz.Put(prm)
```
And got:
```
BenchmarkBlobovniczas_Put/tree=1x0-8                  87          12323530 ns/op           33656 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  92          13031141 ns/op           33912 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  84          12944640 ns/op           33466 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 93          12600201 ns/op           33818 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 88          12914871 ns/op           33901 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 88          12480286 ns/op           33302 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  81          12740758 ns/op           34692 B/op        111 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  93          13036401 ns/op           34883 B/op        111 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  92          13253987 ns/op           35103 B/op        111 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  91          13660381 ns/op           37916 B/op        179 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  88          15612270 ns/op           37448 B/op        179 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  85          15245248 ns/op           38210 B/op        180 allocs/op
```
Then `const objSizeLimit = 1` for the fun of it:
```
BenchmarkBlobovniczas_Put/tree=1x0-8                  84          13757404 ns/op           12682 B/op         68 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  80          14032831 ns/op           12531 B/op         68 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  82          13922973 ns/op           12701 B/op         68 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 94          14235156 ns/op           12628 B/op         69 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 85          14489805 ns/op           12677 B/op         68 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 81          14262814 ns/op           12712 B/op         68 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  81          14078772 ns/op           12554 B/op         99 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  88          14096657 ns/op           12192 B/op        100 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  96          14447775 ns/op           12224 B/op         99 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  93          14432768 ns/op           20945 B/op        164 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  93          13946014 ns/op           20724 B/op        164 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  81          14332493 ns/op           21495 B/op        167 allocs/op
```
4×4 tests take noticeably more time to initialize, probably related to #2215.

**Comment by roman-khimov** [comment]
And for everyone who loves Bolt's `Batch()`, 4K rawdata again:
```
BenchmarkBlobovniczas_Put/tree=1x0-8                  79          13972488 ns/op           32855 B/op         76 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  75          14311804 ns/op           32893 B/op         76 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                  70          14741192 ns/op           33038 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 74          21875172 ns/op           33024 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 51          19937993 ns/op           33017 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                 60          19911600 ns/op           33390 B/op         77 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  57          19892171 ns/op           34676 B/op        112 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  55          20462990 ns/op           35634 B/op        112 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                  51          20171586 ns/op           35801 B/op        112 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  74          16178143 ns/op           37526 B/op        177 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  82          15692310 ns/op           38175 B/op        180 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                  70          15463406 ns/op           38270 B/op        181 allocs/op
```
And now :magic_wand::
```
--- a/pkg/local_object_storage/blobovnicza/put.go
+++ b/pkg/local_object_storage/blobovnicza/put.go
@@ -52,7 +52,7 @@ func (b *Blobovnicza) Put(prm PutPrm) (PutRes, error) {
        bucketName := bucketForSize(sz)
        key := addressKey(prm.addr)
 
-       err := b.boltDB.Batch(func(tx *bbolt.Tx) error {
+       err := b.boltDB.Update(func(tx *bbolt.Tx) error {
                if b.full() {
                        return ErrFull
                }
```
Which leads to
```
BenchmarkBlobovniczas_Put/tree=1x0-8                 702           2028573 ns/op           34427 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                 666           1835332 ns/op           34542 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=1x0-8                 670           1910506 ns/op           34466 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                649           2054211 ns/op           34187 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                633           1892979 ns/op           34329 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                662           2001137 ns/op           34367 B/op         78 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                 556           1927446 ns/op           34935 B/op        103 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                 634           1939887 ns/op           34880 B/op        104 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                 616           1912483 ns/op           35060 B/op        104 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                 483           3807073 ns/op           37531 B/op        153 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                 532           3495096 ns/op           37740 B/op        152 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                 362           4435523 ns/op           36668 B/op        156 allocs/op
```

**Comment by cthulhu-rider** [comment]
> But it's intended for small objects, so I've made

yep, I got excited with 1M which is default for storage node. Changed to 4K and got similar results, so updated the test

> And for everyone who loves Bolt's `Batch()`

personally, i still have not had the opportunity to test the benefits of native batching in Bolt in practice, but, according to the results, its benefits are doubtful in blobovnicza tree

---

I think we have a sufficient evidence base to try to optimize the data structure in the form of a single database with custom batching, huh? @roman-khimov @carpawell

**Comment by cthulhu-rider** [comment]
> Want more fun?

not really, swing in one direction or the other

> Add some threading into the mix

i can add parallelism (as option or not)

**Comment by roman-khimov** [comment]
> not really, swing in one direction or the other

It's not in fact. It's very very consistent and predictable. But the point remains, bbcz tree adds zero value.

**Comment by roman-khimov** [comment]
We can add all modes, merge this one (just to save it for the future) and then take a :hocho: and do #2453.

**Comment by cthulhu-rider** [comment]
added parallel runs d22c757624fc19a31fa098da35d6179090c87e70

**Review by carpawell — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
