### PR TITLE
Add github run url to Allure report

### PR DESCRIPTION
**Pull request by MaxGelbakhiani**

### CODE REVIEW

**Review by roman-khimov — APPROVED** [review]

**Comment by roman-khimov** [comment]
But maybe this can be done in https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/?

**Comment by carpawell** [comment]
> But maybe this can be done in https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/?

Had the same thoughts but did not want to stop the PR. But really had.

**Comment by MaxGelbakhiani** [comment]
> But maybe this can be done in https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/?

Reasonable. But it looks like I have no rights to push to gh-push-allure-report-to-neofs. Could you check this?

**Comment by MaxGelbakhiani** [comment]
Opened  https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/pull/5

**Comment by MaxGelbakhiani** [comment]
Opened https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/pull/5

**Pull request closed without merging**
