### PR TITLE
[SUPPORT] Fix/`object hash` panic in CLI

### LINKED ISSUE #2079: neofs-cli object hash leads to 'panic: runtime error: invalid memory address or nil pointer dereference'
## Steps to Reproduce (for bugs)
1. Create container
```
neofs-cli --rpc-endpoint 172.26.162.50:8080 --wallet wallet.json container create --name f_test_1 --policy "REP 2 IN X CBF 2 SELECT 2 FROM * AS X" --await
Enter password >
container ID: 2tE4gM4zVdk3StGC24Yd3LPXL4bxNvCjzqcxUdqNnRdk
```
2. PUT object
```
neofs-cli --rpc-endpoint 172.26.162.50:8080 -w wallet.json object put --file /tmp/object100M-1.sample --cid 2tE4gM4zVdk3StGC24Yd3LPXL4bxNvCjzqcxUdqNnRdk
Enter password >
 104857600 / 104857600 [===========================================================================================================================================================================] 100.00% 24s
[/tmp/object100M-1.sample] Object successfully stored
  OID: 2SDJJ9cwoZteddtdEQ7TNQ41AJvm7yK57AnjLCtN846L
  CID: 2tE4gM4zVdk3StGC24Yd3LPXL4bxNvCjzqcxUdqNnRdk
```
3. Try to get hash of the object
```
neofs-cli object hash --rpc-endpoint '172.26.162.50:8080' --wallet 'wallet.json' --cid '2tE4gM4zVdk3StGC24Yd3LPXL4bxNvCjzqcxUdqNnRdk' --oid '2SDJJ9cwoZteddtdEQ7TNQ41AJvm7yK57AnjLCtN846L' --type sha256
Enter password >
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa502ac]

goroutine 1 [running]:
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).prepareRequest(0x0?, {0xe60aa0?, 0xc000382060?}, 0xc00033eb40?)
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.7/client/common.go:177 +0xac
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).ObjectHead(0x0, {0xe620a0?, 0xc00013c000}, {{{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...}, ...})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.7/client/object_get.go:433 +0x15f
github.com/nspcc-dev/neofs-node/cmd/neofs-cli/internal/client.HeadObject({{{0x0}, {0x0}, 0x0, 0x0, {0x14bff20, 0x0, 0x0}}, {{{0x1b, 0xfb, 0x14, ...}, ...}}, ...})
        github.com/nspcc-dev/neofs-node/cmd/neofs-cli/internal/client/client.go:621 +0x3df
github.com/nspcc-dev/neofs-node/cmd/neofs-cli/modules/object.getObjectHash(0x147c700?, {0xd15baa?, 0xa?, 0xa?})
        github.com/nspcc-dev/neofs-node/cmd/neofs-cli/modules/object/hash.go:75 +0x2fd
github.com/spf13/cobra.(*Command).execute(0x147c700, {0xc00033f220, 0xa, 0xa})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1476d00)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/nspcc-dev/neofs-node/cmd/neofs-cli/modules.Execute()
        github.com/nspcc-dev/neofs-node/cmd/neofs-cli/modules/root.go:52 +0x25
main.main()
        github.com/nspcc-dev/neofs-node/cmd/neofs-cli/main.go:6 +0x17
```
**Version:**
```
NeoFS CLI
Version: v0.34.0-9-g2e891768
GoVersion: go1.18.4
```

### PR DESCRIPTION
**Pull request by carpawell**
Closes #2079.

### CODE REVIEW

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing. Build number is 3688

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from <a href="https://http.t5.fs.neo.org/get/FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/9dsbEsp5swu4K26F3VSVJPxjxocyZdcxB2kvKLrs5RpQ">link</a>. Untar and use `allure open` to watch the report

**Review by fyrchik — APPROVED** [review]

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing. Build number is 3700

**Comment by sami-nspcc** [comment]
I am running integration tests

**Pull request merged**
