### PR TITLE
services/policer: make replicator pool nonblocking

### PR DESCRIPTION
**Pull request by fyrchik**
Another possible OOM cause.

Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

### CODE REVIEW

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I am running integration tests

**Review by acid-ant — APPROVED** [review]

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I have recieved a notification of a new pull request. I am starting the build of images and binaries for further testing.

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/FWSJmidqhUASkFMApCc3H62X8kcgB4gs89gUaarfSBCt Untar and use `allure open` to watch the report

**Comment by sami-nspcc** [comment]
I am running integration tests

**Comment by carpawell** [comment]
Could you, please, clarify the idea a little? There is a hypothesis about the blocking pool calls that lead to OOM, and you add `Sleep` and retries instead of the blocks, how that could help?

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/8f1eJPf558APGQwMyzPfTXZxFsZv9UjkoLqYi5mwusfD Untar and use `allure open` to watch the report

**Comment by sami-nspcc** [comment]
Test run is finished. Please download the tarball from `st*.t5.fs.neo.org`:  FszwwAx3VznDysQGxBUMRj1zj3zp8VcohorVDnunrviV/FACx6GcbYaZMS6whysvwc5hPhkAuUyEm6qkQaeFpBKTN Untar and use `allure open` to watch the report

**Comment by carpawell** [comment]
> Without NonBlocking lots of goroutines can wait in Submit

Oh, did not notice that you changed the _different_ pools in that PR.

**Review by carpawell — APPROVED** [review]

**Review by carpawell — APPROVED** [review]

**Pull request closed without merging**
